### ISSUE TITLE
参加希望です

### ISSUE THREAD

**Issue by yoichigmf** [miurahr/gdal_docs_ja#1]
QGISのドキュメント日本語化がなかなか進まないのでこちらにさける力量があやしいですが、GDALはQGISの基本部分でもあるので翻訳作業参加希望します。

**Comment by miurahr** [comment]
リポジトリに追加しました。参加依頼のメールなどがいっているとおもいますので、手続ください。

**Comment by miurahr** [comment]
ありがとうございます。QGISって、transifexで翻訳されていますよね。 
GDALもそのほうがよいでしょうか。

OmegaTを使うメリットとして、オフラインでも実施できる、手持ちの辞書を動的にひける、オンライン自動翻訳がつかえる、ということがあります。

**Comment by yoichigmf** [comment]
QGISの翻訳はtransifexになる前はQtの翻訳ツールをつかってました。こちらのほうがプログラムの画面中のどこの文言なのかわかるので私としては翻訳しやすかったです。Transifexになると参加者は増えますが。OmegaTは使ったことがないのでちょっと勉強してみます。

**Comment by miurahr** [comment]
わたしは、Transifexでも、ダウンロードして、デスクトップツールで翻訳してアップロードしています。

入門書についてのIssueを作成して、Pinしました。ご確認ください。

オンライン機械翻訳エンジンや、利用できる辞書、プラグインについての記事は作成中です。
