### ISSUE TITLE
参加希望です

### ISSUE THREAD

**Issue by wata909** [miurahr/gdal_docs_ja#3]
三浦さん、岩崎です。
参加、希望します。

**Comment by miurahr** [comment]
ありがとうございます。

リポジトリの書き込みアクセス権を付与しました。
OmegaTで https://github.com/miurahr/gdal_docs_ja を指定してください。
IDやパスワードをきかれましたら、岩崎さんのgithub アカウントのID/Passまたは、MFAを設定している場合は、ID / personal access tokenを指定してください。

**Comment by tohka** [comment]
有田と申します。
どこまで協力できるかわかりませんが、参加を希望します。
Geoweek and Weekend も参加予定です。

**Comment by miurahr** [comment]
@tohka アクセス権を付与しました。

**Comment by tohka** [comment]
@miurahr ありがとうございます
